DB_URL=postgresql://postgres:password@postgres:5432/subscription_backend?sslmode=disable
name = init_schema

new_migration:
	migrate create -ext sql -dir db/migration -seq $(name)

migrateup:
	migrate -path db/migration -database "$(DB_URL)" -verbose up

migratedown:
	migrate -path db/migration -database "$(DB_URL)" -verbose down
