version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_backend
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 5053:8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
  
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    # volumes:
    #   - ./db-data/rabbitmq/:/var/lib/rabbitmq/
  
  user-service:
    build:
      context: ./../subscription-service
      dockerfile: subscription-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=subscription_backend sslmode=disable timezone=UTC connect_timeout=5"
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Movido Verlag"
      FROM_ADDRESS: alefewyimer2@gmail.com
      
      